### ISSUE TITLE
ProxySQL support (COM_STMT_CLOSE issue)

### ISSUE THREAD

**Issue by ckmjreynolds** [vapor/mysql-nio#15]
- fluent-mysql-driver - `.exact("4.0.0-beta.2.2")),`
- Connecting through ProxySQL 2.0.8 to MariaDB 10.4.10 (Galera cluster).

ProxySQL terminates connections due to "[ERROR] Unexpected packet from client".

Wireshark suggests a COM_STMT_CLOSE is sent before the "Response OK".
![image](https://user-images.githubusercontent.com/46268121/71133540-75ae0e00-21c0-11ea-9a70-55de999b754e.png)

Debugging suggests an EOF packet is received but this is not shown in the packet capture, commenting out the COM_STMT_CLOSE resolves the issue.

checkouts/mysql-nio/Sources/MySQLNIO/MySQLQueryCommand.swift:141
```swift
                return .noResponse
/*                var packet = MySQLPacket()
                MySQLProtocol.COM_STMT_CLOSE(statementID: self.ok!.statementID).encode(into: &packet)
                if let error = self.lastUserError {
                    throw error
                } else {
                    return .init(response: [packet], done: true, resetSequence: true)
                }
*/
```

**Comment by ckmjreynolds** [comment]
Please note, commenting out COM_STMT_CLOSE is not a "fix" it simply gets past the "[ERROR] Unexpected packet from client" and associated termination of the connection by ProxySQL.

**Comment by ckmjreynolds** [comment]
This could stem from the lack of support for CLIENT_DEPRECATE_EOF which this code expects: https://github.com/sysown/proxysql/issues/2119

**Comment by gwynne** [comment]
It looks like ProxySQL added the missing support back in October 2020 (https://github.com/sysown/proxysql/pull/3123), so I'm gonna close this out. Please feel free to reopen it if this is still happening!
