### ISSUE TITLE
Timezone support

### ISSUE THREAD

**Issue by t-ae** [vapor/mysql-nio#43]
Currently it seems `Date` is encoded/decoded as GMT+00:00.
[encode](https://github.com/vapor/mysql/blob/02edf2b060ea9ac6cc1bd924563052f61ded35b2/Sources/MySQL/Connection/MySQLData.swift#L557)/[decode](https://github.com/vapor/mysql/blob/02edf2b060ea9ac6cc1bd924563052f61ded35b2/Sources/MySQL/Connection/MySQLData.swift#L527)
Now I want to store date as local time zone. So I want to make the `TimeZone`s above configurable.

There are two way to accomplish this.

1. Set `TimeZone` via `MySQLDatabaseConfig`
2. Get database's time zone while `MySQLConnection.authenticate` and use it

Eitherway we must provide time zone to `convertFromMySQLTime` and `convertToMySQLTime`.
Any ideas?

**Comment by gwynne** [comment]
Closing this out as not relevant at this point.
