### ISSUE TITLE
Protocol mismatch not detected

### ISSUE THREAD

**Issue by vitkabele** [vapor/mysql-nio#60]
### Describe the bug

I accidentally tried to connect to the port `33060` of the MySQL server, which is used for [protocol X](https://dev.mysql.com/doc/mysql-port-reference/en/mysql-ports-reference-tables.html) of the MySQL. This port returns version 11 of the protocol and so the handshake should fail with reasonable error message (as implemented [here](https://github.com/vapor/mysql-nio/blob/main/Sources/MySQLNIO/Protocol/MySQLProtocol%2BHandshakeV10.swift#L55)).

The problem is, that this check somehow passed and the application crashed later with cryptic message:
```
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file MySQLNIO/MySQLConnectionHandler.swift, line 416
```
with increased verbosity:
```
[ codes.vapor.application ] [ DEBUG ] Opening new connection to [IPv6]localhost/::1:33060 [database-id: mysql] (MySQLNIO/MySQLConnection.swift:17)
[ codes.vapor.application ] [ TRACE ] MySQLPacketDecoder.decode: [11, 8, 5, 26, 0]... (err: false, ok: false, eof: false) [database-id: mysql] (MySQLNIO/Packet/MySQLPacketDecoder.swift:30)
[ codes.vapor.application ] [ TRACE ] Handle handshake packet [database-id: mysql] (MySQLNIO/MySQLConnectionHandler.swift:62)
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file MySQLNIO/MySQLConnectionHandler.swift, line 416

```

### To Reproduce

Try to connect to the port `33060` instead of the default `3306`

### Expected behaviour

Meaningful error message should be printed.

### Environment

* Vapor Framework version: 4.39.2
* Vapor Toolbox version: 18.3.2
* OS version: macOS 11
* MySQL version: 8.0.23

**Comment by gwynne** [comment]
The bytes of the packet being decoded in your log message do not constitute a valid handshake packet at all - the X protocol doesn't appear to use the handshake, as best I can determine from the (unbelievably unhelpful) protocol documentation and some experimentation. MySQLNIO's current reaction to being connected to a port listening on the X protocol with a 5.7 server is the same as that of the commandline `mysql` client in my testing - it just hangs waiting for the server handshake. An 8.0 sever does sent that 5-byte initial packet, but the format of that packet doesn't match anything in _either_ protocol's lexicon, as far as I can tell. MySQLNIO correctly rejects it in my testing with the `.invalidProtocolVersion(11)` error. Please let me know if you're still experiencing this and I'll reopen the issue.
