### ISSUE TITLE
error build: The package product 'Crypto' requires minimum platform version 13.0 for the iOS platform, but this target supports 11.0

### ISSUE THREAD

**Issue by iScript** [vapor/mysql-nio#81]
error build: The package product 'Crypto' requires minimum platform version 13.0 for the iOS platform, but this target supports 11.0

**Comment by 0xTim** [comment]
MySQL doesn't support iOS at the moment - if you want to use it, feel free to submit a PR to add iOS 13 to the platforms array in Package.swift
