### ISSUE TITLE
Link to MSQLNIO API in Readme.md gives error 403

### ISSUE THREAD

**Issue by randumami** [vapor/mysql-nio#85]
Hi
When clicking on the link to MYSQLNIO API, under the heading API Docs, readme.md -  I get en error 403 Forbidden.

Can you help with the correct link to the documentation?

The full error code is:
403 Forbidden

Code: AccessDenied
Message: Access Denied
RequestId: R7FF9D4VCD0GAXPT
HostId: UxuQc4A9eph0bkmDZ1kx99JaRIB/7doa6yyPODRk7+eJQjV0vyX7VijRwv7fg8dm3fVZliNI8K8=
An Error Occurred While Attempting to Retrieve a Custom Error Document

Code: AccessDenied
Message: Access Denied

**Comment by 0xTim** [comment]
Thanks, we're currently migrating to DocC - for now you can find the old docs at https://legacy.api.vapor.codes/mysql-nio/main/MySQLNIO/

**Comment by gwynne** [comment]
The API docs link has been updated with the correct URL
